name: Perform Automatic Merge

 

on:
  pull_request:
    types:
      - opened
      - synchronize

 

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

 

      - name: Perform Automatic Merge
        run: |
          gh pr merge 2 -m
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
